# Site settings
title: 'Frasco: Jekyll Quick Starter'
description: Quick starter for Jekyll including full setup for Sass, PostCSS, Autoprefixer, stylelint, TypeScript, Webpack, ESLint, imagemin, Browsersync, etc.
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/frasco' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

compress_html:
  # clippings: all
  comments: all
  # endings: all
  ignore:
    envs: [development]
  # blanklines: true
  # profile: true
  # startings: [html, head, body]

twitter:
  id: ixkaito

facebook:
  admin: 1047363919

exclude:
  - Gemfile
  - Gemfile.lock
  - imagemin.js
  - LICENSE
  - node_modules/
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
  - yarn.lock
